config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get '/',                        to: 'sample#index'
    get 'index',                    to: 'sample#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
    resources :products,            only: [:show]
    resources :categories,          only: [:show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spree/product_decorator.rb
module Spree::ProductDecorator
  def related_products
    Spree::Product.in_taxons(taxons).includes(master: [:default_price, :images]).where.not(id: id).distinct
  end

  Spree::Product.prepend self
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  def show
    @taxon = Spree::Taxon.find(params[:id])
    @taxonomies = Spree::Taxonomy.includes(:root)
    @products = @taxon.products.includes(master: [:default_price, :images])
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  MAX_RELATED_PRODUCTS = 9

  def show
    @product = Spree::Product.find(params[:id])
    @related_products = @product.related_products.limit(MAX_RELATED_PRODUCTS)
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "BIGBAG Store"
    if page_title.blank?
      base_title
    else
      "#{page_title} - #{base_title}"
    end
  end
end

app/views/layouts/_footer.html.erb
<!-- COPY RIGHT -->
<div id="footer" class="copyRight clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-7 col-xs-12">
        <p>&copy; 2016-<%= Time.current.year %> Copyright Potepan Store .</p>
      </div>
      <div class="col-sm-5 col-xs-12">
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_head.html.erb
<title><%= full_title(yield(:title)) %></title>
<%= csrf_meta_tags %>
<!-- SITE TITTLE -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- PLUGINS CSS STYLE -->
<!-- GOOGLE FONT -->
<%= stylesheet_link_tag "application", 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', :media => "all" %>
<!-- CUSTOM CSS -->
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/_header.html.erb
<div class="header clearfix">
  <!-- TOPBAR -->
  <div class="topBar">
    <div class="container">
      <div class="row">
        <div class="col-md-6 hidden-sm hidden-xs">
          <ul class="list-inline">
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          </ul>
        </div>
        <div class="col-md-6 col-xs-12">
          <ul class="list-inline pull-right">
            <li class="dropdown searchBox">
              <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
              <ul class="dropdown-menu dropdown-menu-right">
                <form id="form01" action="product-grid-left-sidebar.html" method="post">
                  <li>
                    <span class="input-group">
                      <input type="text" name="searchWord" class="form-control" placeholder="Search…" aria-describedby="basic-addon2">
                    <span onclick="FormSubmit();" class="input-group-addon addPointer" id="basic-addon2">検索</span>
                    </span>
                  </li>
                </form>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown disabled"><i class="fa fa-shopping-cart"></i></a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <!-- NAVBAR -->
  <nav class="navbar navbar-main navbar-default" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to(potepan_path, class: 'navbar-brand') do %>
          <%= image_tag("img/logo.png", :alt => "") %>
        <% end %>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li class="<%= 'active' if current_page?(potepan_path) %>">
            <%= link_to("Home", potepan_path) %>
          </li>
          <li class="dropdown megaDropMenu active">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true" aria-expanded="false">Shop</a>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div>
  </nav>
</div>

app/views/layouts/_modals.html.erb
<!-- LOGIN MODAL -->
<div class="modal fade" id="login" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">log in</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="login-email">Enter Email</label>
            <input type="email" class="form-control" id="login-email">
          </div>
          <div class="form-group">
            <label for="login-password">Password</label>
            <input type="password" class="form-control" id="login-password">
          </div>
          <div class="checkbox">
            <label>
              <input type="checkbox"> Remember Me
            </label>
          </div>
          <button type="submit" class="btn btn-primary btn-block">log in</button>
          <button type="button" class="btn btn-link btn-block">Forgot Password?</button>
        </form>
      </div>
    </div>
  </div>
</div>
<!-- SIGN UP MODAL -->
<div class="modal fade" id="signup" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">Create an account</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="signup-email">Enter Email</label>
            <input type="email" class="form-control" id="signup-email">
          </div>
          <div class="form-group">
            <label for="signup-password">Password</label>
            <input type="password" class="form-control" id="signup-password">
          </div>
          <div class="form-group">
            <label for="signup-password-confirmation">Confirm Password</label>
            <input type="password" class="form-control" id="signup-password-confirmation">
          </div>
          <button type="submit" class="btn btn-primary btn-block">Sign up</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/head' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/potepan/categories/_filter_area.html.erb
<div class="col-md-9 col-sm-8 col-xs-12">
  <div class="row filterArea">
    <div class="col-xs-6">
      <select name="guiest_id1" id="guiest_id1" class="select-drop">
        <option value="0">Sort</option>
        <option value="1">Best Selling</option>
        <option value="2">Newest to Oldest</option>
        <option value="3">Price: Low to High</option>
        <option value="3">Price: High to Low</option>
      </select>
    </div>
    <div class="col-xs-6">
      <div class="btn-group pull-right" role="group">
        <a href="#" id="grid" class="btn btn-default active"><span class="glyphicon glyphicon-th"></span>Grid</a>
        <a href="#" id="list" class="btn btn-default"><span class="glyphicon glyphicon-th"></span>List</a>
      </div>
    </div>
  </div>
</div>

app/views/potepan/categories/_product_box.html.erb
<div class="col-md-9 col-sm-8 col-xs-12">
  <div class="row">
    <% products.each do |product| %>
      <div class="col-sm-4 col-xs-12">
        <div class="productBox">
          <%= link_to potepan_product_path(product.id) do %>
            <div class="productImage clearfix">
              <%= image_tag(product.display_image.attachment(:large)) %>
            </div>
            <div class="productCaption clearfix">
              <h5><%= product.name %></h5>
              <h3><%= product.display_price %></h3>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/potepan/categories/_sidebar.html.erb
<div class="col-md-3 col-sm-4 col-xs-12 sideBar">
  <!-- CATEGORY SECTION -->
  <div class="panel panel-default">
    <div class="panel-heading">category</div>
    <div class="panel-body">
      <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
        <ul class="nav navbar-nav side-nav">
          <% taxonomies.each do |taxonomy| %>
            <li>
              <%= link_to "javascript:void(0)", data: {toggle: "collapse", target: "#category-#{taxonomy.id}"} do %>
                <%= taxonomy.name %><i class="fa fa-plus"></i>
              <% end %>
              <ul id="category-<%= taxonomy.id %>" class="collapse collapseItem">
                <% taxonomy.root.leaves.each do |leaf| %>
                  <li>
                    <%= link_to potepan_category_path(leaf.id) do %>
                      <i class="fa fa-caret-right" aria-hidden="true"></i><%= leaf.name %> <span>(<%= leaf.products.count %>)</span>
                    <% end %>
                  </li>
                <% end %>
              </ul>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <%#
  <!-- COLOR SECTION -->
  <div class="panel panel-default filterNormal">
    <div class="panel-heading">color</div>
    <div class="panel-body">
      <ul class="list-unstyled">
        <li><a href="#">Black<span>(15)</span></a></li>
        <li><a href="#">White<span>(10)</span></a></li>
        <li><a href="#">Red<span>(7)</span></a></li>
        <li><a href="#">Blue<span>(12)</span></a></li>
        <li><a href="#">Orange<span>(12)</span></a></li>
      </ul>
    </div>
  </div>
  <!-- SIZE SECTION -->
  <div class="panel panel-default filterNormal">
    <div class="panel-heading">size</div>
    <div class="panel-body">
      <ul class="list-unstyled clearfix">
        <li><a href="#">S<span>(15)</span></a></li>
        <li><a href="#">M<span>(10)</span></a></li>
        <li><a href="#">L<span>(7)</span></a></li>
        <li><a href="#">XL<span>(12)</span></a></li>
      </ul>
    </div>
  </div>
  %>
</div>

app/views/potepan/categories/show.html.erb
<% provide(:title, "#{@taxon.name} - BIGBAG Store") %>
<div class="main-wrapper">
  <!-- LIGHT SECTION -->
  <%= render 'shared/light_section_header', taxon: @taxon %>
  <!-- MAIN CONTENT SECTION -->
  <section class="mainContent clearfix productsContent">
    <div class="container">
      <div class="row">
        <%= render 'sidebar', taxonomies: @taxonomies %>
        <%= render 'filter_area', taxon: @taxon %>
        <%= render 'product_box', products: @products %>
      </div>
    </div>
  </section>
  <!-- LIGHT SECTION -->
  <%= render 'shared/light_section_partners_logo' %>
</div>

app/views/potepan/products/_light_section.html.erb
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= product.name %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li class="active"><%= link_to("Home", potepan_path) %></li>
          <li class="active"><%= product.name %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

app/views/potepan/products/_related_products.html.erb
<div class="row productsContent">
  <div class="col-xs-12">
    <div class="page-header">
      <h4>RELATED PRODUCTS</h4>
    </div>
  </div>
  <div class="col-xs-12">
    <div class="productBox owl-carousel featuredProductsSlider">
      <% related_products.each do |related_product| %>
        <%= link_to potepan_product_path(related_product.id) do %>
          <div class="slide">
            <div class="productImage clearfix">
              <%= image_tag related_product.display_image.attachment.url %>
            </div>
            <div class="productCaption clearfix">
              <h5><%= related_product.name %></h5>
              <h3><%= related_product.display_price %></h3>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/potepan/products/show.html.erb
<% provide(:title, "#{@product.name} - BIGBAG Store") %>
<div class="main-wrapper">
  <!-- LIGHT SECTION -->
  <%= render 'light_section', product: @product %>
  <!-- MAIN CONTENT SECTION -->
  <section class="mainContent clearfix">
    <div class="container">
      <div class="row singleProduct">
        <div class="col-xs-12">
          <div class="media">
            <div class="media-left productSlider">
              <div id="carousel" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                  <% @product.images.each_with_index do |image, index| %>
                    <div class="item <%= 'active' if index.zero? %>" data-thumb="<%= index %>">
                      <%= image_tag(image.attachment(:large)) %>
                    </div>
                  <% end %>
                </div>
              </div>
              <div class="clearfix">
                <div id="thumbcarousel" class="carousel slide" data-interval="false">
                  <div class="carousel-inner">
                    <% @product.images.each_with_index do |image, index| %>
                      <div data-target="#carousel" data-slide-to="<%= index %>" class="thumb">
                        <%= image_tag(image.attachment(:small)) %>
                      </div>
                    <% end %>
                  </div>
                  <a class="left carousel-control" href="#thumbcarousel" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                  </a>
                  <a class="right carousel-control" href="#thumbcarousel" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                  </a>
                </div>
              </div>
            </div>
            <div class="media-body">
              <ul class="list-inline">
                <li>
                  <%= link_to potepan_category_path(@product.taxons.first.id) do %>
                    <i class="fa fa-reply" aria-hidden="true"></i>Back to list page
                  <% end %>
                </li>
              </ul>
              <h2><%= @product.name %></h2>
              <h3><%= @product.display_price %></h3>
              <p><%= @product.description %></p>
              <span class="quick-drop">
                <select name="guiest_id3" id="guiest_id3" class="select-drop">
                  <option value="0">S</option>
                  <option value="1">M</option>
                  <option value="2">L</option>
                  <option value="3">XL</option>
                </select>
              </span>
              <span class="quick-drop resizeWidth">
                <select name="guiest_id4" id="guiest_id4" class="select-drop">
                  <option value="1">1</option>
                  <option value="2">2</option>
                  <option value="3">3</option>
                </select>
              </span>
              <div class="btn-area">
                <a href="#" class="btn btn-primary btn-block">Add to cart<i class="fa fa-angle-right" aria-hidden="true"></i></a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- RELATED PRODUCTS -->
      <%= render partial: 'related_products', locals: {related_products: @related_products} %>
    </div>
  </section>
</div>

app/views/potepan/sample/blog_single_left_sidebar.html.erb
<div class="main-wrapper">
  <!-- LIGHT SECTION -->
  <section class="lightSection clearfix pageHeader">
    <div class="container">
      <div class="row">
        <div class="col-xs-6">
          <div class="page-title">
            <h2>Blog Single sidebar</h2>
          </div>
        </div>
        <div class="col-xs-6">
          <ol class="breadcrumb pull-right">
            <li>
              <a href="index.html">Home</a>
            </li>
            <li class="active">Blog Single sidebar</li>
          </ol>
        </div>
      </div>
    </div>
  </section>
  <!-- MAIN CONTENT SECTION -->
  <section class="mainContent clearfix blogPage singleBlog">
    <div class="container">
      <div class="row">
        <div class="col-md-9 col-sm-8 col-md-push-3 col-sm-push-4 col-xs-12">
          <div class="row">
            <div class="col-xs-12">
              <div class="thumbnail">
                <%= image_tag("img/blog/blog-01.jpg", :alt => "blog-image") %>
                <div class="caption">
                  <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                      <h3>記事タイトル </h3>
                      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>

                      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. </p>

                      <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. </p>

                      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. </p>

                      <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. </p>
                    </div>
                  </div>
                </div>
                <ul class="pager">
                  <li class="previous"><a href="#">前の記事へ</a></li>
                  <li class="next"><a href="#">次の記事へ</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-3 col-sm-4 col-md-pull-9 col-sm-pull-8 col-xs-12 sideBar">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search" aria-describedby="basic-addon2">
            <a href="#" class="input-group-addon" id="basic-addon2"><i class="fa fa-search"></i></a>
          </div>
          <div class="panel panel-default">
            <div class="panel-heading">カテゴリー</div>
            <div class="panel-body">
              <ul class="list-unstyle sidebar-list">
                <li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i>アクセサリー <span>(6)</span></a></li>
                <li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i>バッグ <span>(6)</span></a></li>
                <li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i>洋服 <span>(25)</span></a></li>
                <li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i>ベッド &amp; バス <span>(2)</span></a></li>
                <li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i>スイミング <span>(5)</span></a></li>
                <li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i>スポーツウェア &amp; シューズ <span>(3)</span></a></li>
              </ul>
            </div>
          </div>
          <div class="panel panel-default recentBlogPosts">
            <div class="panel-heading">最新記事</div>
            <div class="panel-body">
              <div class="media">
                <a class="media-left" href="blog_single_right_sidebar.html">
                  <%= image_tag("img/blog/blog-small-01.jpg", :class => "media-object", :alt => "Image") %>
                </a>
                <div class="media-body">
                  <h4 class="media-heading"><a href="blog_single_right_sidebar.html">記事タイトル（20文字）</a></h4>
                  <p><i class="fa fa-calendar" aria-hidden="true"></i>2016/5/5</p>
                </div>
              </div>
              <div class="media">
                <a class="media-left" href="blog_single_right_sidebar.html">
                  <%= image_tag("img/blog/blog-small-02.jpg", :class => "media-object", :alt => "Image") %>
                </a>
                <div class="media-body">
                  <h4 class="media-heading"><a href="blog_single_right_sidebar.html">記事タイトル（20文字）</a></h4>
                  <p><i class="fa fa-calendar" aria-hidden="true"></i>2016/5/5</p>
                </div>
              </div>
              <div class="media">
                <a class="media-left" href="blog_single_right_sidebar.html">
                  <%= image_tag("img/blog/blog-small-03.jpg", :class => "media-object", :alt => "Image") %>
                </a>
                <div class="media-body">
                  <h4 class="media-heading"><a href="blog_single_right_sidebar.html">記事タイトル（20文字）</a></h4>
                  <p><i class="fa fa-calendar" aria-hidden="true"></i>2016/5/5</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/potepan/sample/checkout_complete.html.erb
<div class="main-wrapper">
  <!-- LIGHT SECTION -->
  <section class="lightSection clearfix pageHeader">
    <div class="container">
      <div class="row">
        <div class="col-xs-6">
          <div class="page-title">
            <h2>thanks message</h2>
          </div>
        </div>
        <div class="col-xs-6">
          <ol class="breadcrumb pull-right">
            <li>
              <a href="index.html">Home</a>
            </li>
            <li class="active">thanks message</li>
          </ol>
        </div>
      </div>
    </div>
  </section>
  <!-- MAIN CONTENT SECTION -->
  <section class="mainContent clearfix setp5">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <div class="thanksContent">
            <h2>Thank You !! <small>ご注文ありがとうございます。</small></h2>
            <h3>Shipping Details</h3>
            <div class="thanksInner">
              <div class="row">
                <div class="col-sm-6 col-xs-12 tableBlcok">
                  <address>
                    <span>Shipping address:</span> <a href="mailto:potepan@potepancamp.com">potepan@potepancamp.com</a> <br>
                    <span>Email:</span> <a href="mailto:potepan@potepancamp.com">potepan@potepancamp.com</a> <br>
                    <span>Phone:</span> +884 5452 6432
                  </address>
                </div>
                <div class="col-sm-6 col-xs-12">
                  <div class="well">
                    <h2><small>Order ID</small>9547</h2>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/shared/_light_section_header.html.erb
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= taxon.name %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li class="active"><%= link_to("Home", potepan_path) %></li>
          <li>
            <a href="#">shop</a>
          </li>
          <li class="active"><%= taxon.name %></li>
        </ol>
      </div>
    </div>
  </div>
</section>